---
project_repos:
  - https://github.com/rhew/pi-hole.git
  - https://github.com/rhew/private-torrent-downloader.git
  - https://github.com/rhew/led-pixel-wall.git

service_data_dirs:
  - /home/rhew/media
  - /home/rhew/media/complete
  - /home/rhew/media/incomplete
  - /home/rhew/pi-hole/etc-pihole
  - /home/rhew/pi-hole/etc-dnsmasq.d
  - /home/rhew/private-torrent-downloader/downloads
